[mcp_servers]
content = '''
{
    "mcpServers": {
        "example-stdio-mcp-name": {
            "transport": "stdio", 
            "command": "uv/npx", 
            "args": ["script"]
        },
        "example-tcp-mcp-name": {
            "transport": "streamable_http",
            "url": "http://mcp-server:port/mcp"
        }
     }
}
'''

[model_config]
model_name = ""
api_key = ""
base_url = ""
# 不要给 major_agent 添加工具, 应该把工具给 sub_agent。
# tool_names = [] 
system_prompt = ""

# Embedding Model
embedding_model_name = ""
embedding_api_key = ""
embedding_base_url = ""

# SubAgent model
sub_agent = ["sub_agent_1", "sub_agent_2"]
# inside_tools: shell_exec, internet_search (need tavily api key)
sub_agent_model_config = '''
{
    "sub_agent_1": {
        "model_name": "",
        "api_key": "",
        "base_url": "",
        "system_prompt": "",
        "mcp_tools": ["example-stdio-mcp-name", "..."],
        "inside_tools": [...]
    },
    "sub_agent_2": {
        "model_name": "",
        "api_key": "",
        "base_url": "",
        "system_prompt": "",
        "mcp_tools": ["example-tcp-mcp-name", "..."],
        "inside_tools": [...]
    }
}
'''

tavily_api_key = ""